name: Generate Content Index

on:
  push:
    branches:
      - main
    paths:
      - 'content/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    environment:
      name: github-pages
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install gray-matter

    - name: Generate Index
      run: |
        cat > index.js << 'EOL'
        const fs = require('fs');
        const path = require('path');
        const matter = require('gray-matter');

        const contentDir = 'content';
        const files = fs.readdirSync(contentDir);
        const mdFiles = files.filter(file => file.endsWith('.md'));

        const contentIndex = mdFiles
          .map(file => {
            try {
              const content = fs.readFileSync(path.join(contentDir, file), 'utf-8');
              const { data, content: markdown } = matter(content);
              const firstParagraph = markdown
                .split('\n')
                .find(line => line.trim() && !line.startsWith('#'))
                ?.trim() || '';
              
              return {
                title: data.title,
                file: file,
                description: firstParagraph.slice(0, 200),
                date: data.date,
                tags: data.tags,
                published: data.published
              };
            } catch (error) {
              console.error(`Error processing ${file}:`, error);
              return null;
            }
          })
          .filter(entry => entry !== null && entry.published === true)
          .sort((a, b) => new Date(b.date) - new Date(a.date));

        fs.writeFileSync(
          path.join(contentDir, 'index.json'),
          JSON.stringify(contentIndex, null, 2)
        );
        EOL

        node index.js

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Build site directory
      run: |
        mkdir -p _site/content
        cp content/index.json _site/content/
        cp content/*.md _site/content/

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v3

    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add content/index.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update content index" && git push)
