# .github/workflows/generate-index.yml
name: Generate Content Index

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'  # Triggers on any markdown file change

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Generate content index
      run: |
        # Create the index at root level
        echo "[" > index.json
        first=true
        
        # Find all md files recursively, excluding node_modules and .github
        find . -type f -name "*.md" ! -path "./node_modules/*" ! -path "./.github/*" | while read file; do
          # Remove leading ./ from file path
          file_path=${file#./}
          
          if [ "$first" = false ]; then
            echo "," >> index.json
          fi
          first=false
          
          # Extract frontmatter
          title=$(head -n 5 "$file" | grep "title:" | cut -d ":" -f 2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | sed 's/"/\\"/g')
          date=$(head -n 5 "$file" | grep "date:" | cut -d ":" -f 2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
          tags=$(head -n 5 "$file" | grep "tags:" | cut -d ":" -f 2- | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' | sed 's/\[//g' | sed 's/\]//g')
          
          # Get excerpt (first paragraph after frontmatter)
          excerpt=$(sed '1,/---/d' "$file" | awk 'NF{p=$0}END{print p}' | head -n 1 | sed 's/"/\\"/g')
          
          # Create JSON object
          cat >> index.json << EOF
          {
            "title": "${title:-${file_path%.md}}",
            "file": "$file_path",
            "date": "${date:-$(date -r "$file" "+%Y-%m-%d")}",
            "tags": [${tags:-}],
            "excerpt": "${excerpt:0:150}..."
          }
EOF
        done
        echo "]" >> index.json

    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update content index" && git push)
