name: Test Workflow

on:
  push:
    branches:
      - master  # Change this if your default branch is different
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "Hello World"
