name: Generate Content Index

on:
  push:
    branches:
      - master  # Assuming master is your default branch
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Create Directory and Content
      run: |
        mkdir -p content
        echo "Creating test content if none exists"
        if [ ! -f content/test.md ]; then
          echo '---
          title: Test Post
          date: 2024-10-29
          tags: ["test"]
          ---

          This is a test post.' > content/test.md
        fi

    - name: Install dependencies
      run: |
        npm init -y
        npm install gray-matter

    - name: Generate Index
      run: |
        node -e "
          const fs = require('fs').promises;
          const path = require('path');
          const matter = require('gray-matter');

          async function generateIndex() {
            try {
              const contentDir = 'content';
              const files = await fs.readdir(contentDir);
              const mdFiles = files.filter(file => file.endsWith('.md'));
              
              console.log('Found markdown files:', mdFiles);

              const contentIndex = await Promise.all(
                mdFiles.map(async file => {
                  const content = await fs.readFile(path.join(contentDir, file), 'utf-8');
                  const { data, content: markdown } = matter(content);
                  return {
                    title: data.title || file.replace('.md', ''),
                    file: file,
                    date: data.date ? new Date(data.date).toISOString() : new Date().toISOString(),
                    tags: data.tags || []
                  };
                })
              );

              await fs.writeFile(
                path.join(contentDir, 'index.json'),
                JSON.stringify(contentIndex, null, 2)
              );
              
              console.log('Index generated successfully');
            } catch (error) {
              console.error('Error:', error);
              process.exit(1);
            }
          }

          generateIndex();
        "

    - name: Debug Output
      run: |
        echo "Content directory contents:"
        ls -la content/
        echo "Index.json contents:"
        cat content/index.json

    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add content/index.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update content index" && git push)
